# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy to Azure - api-paddockmonitoring-prod

on:
  push:
    branches:
      - main
    paths:
      - 'paddock-api/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2
      with:
        path: paddock-api

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://tonylukeregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_7455752eb65d4ac19feb781a379979d0 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_5e4455f114c4427e8090e303a8932a4d }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        context: '{{defaultContext}}:paddock-api'
        push: true
        tags: tonylukeregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_7455752eb65d4ac19feb781a379979d0 }}/paddock-monitoring/api:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'api-paddockmonitoring-prod'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_51df4ba4eb574d0195db4c4879057e31 }}
        images: 'tonylukeregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_7455752eb65d4ac19feb781a379979d0 }}/paddock-monitoring/api:${{ github.sha }}'